// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ProductsDishes.DataAccess.Postgres;

#nullable disable

namespace ProductsDishes.DataAccess.Postgres.Migrations
{
    [DbContext(typeof(ProductsDishesDbContext))]
    partial class ProductsDishesDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DailyRationEntityDishEntity", b =>
                {
                    b.Property<Guid>("DailyRationsId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("DishesId")
                        .HasColumnType("uuid");

                    b.HasKey("DailyRationsId", "DishesId");

                    b.HasIndex("DishesId");

                    b.ToTable("DailyRationDishes", (string)null);
                });

            modelBuilder.Entity("ProductsDishes.DataAccess.Postgres.Models.DailyRationEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("DailyRations");
                });

            modelBuilder.Entity("ProductsDishes.DataAccess.Postgres.Models.DishEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.ToTable("Dishes");
                });

            modelBuilder.Entity("ProductsDishes.DataAccess.Postgres.Models.DishIngradientEntity", b =>
                {
                    b.Property<Guid>("DishId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("QuantityGrams")
                        .HasColumnType("numeric");

                    b.HasKey("DishId", "ProductId");

                    b.HasIndex("ProductId");

                    b.ToTable("DishIngredients");
                });

            modelBuilder.Entity("ProductsDishes.DataAccess.Postgres.Models.ProductEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("CaloriesPer100")
                        .HasColumnType("numeric");

                    b.Property<decimal>("CarbsPer100")
                        .HasColumnType("numeric");

                    b.Property<decimal>("FatPer100")
                        .HasColumnType("numeric");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<decimal>("ProteinPer100")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("ProductsDishes.DataAccess.Postgres.Models.UserEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Age")
                        .HasColumnType("integer");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<decimal>("HeightCm")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<decimal>("WeightKg")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("DailyRationEntityDishEntity", b =>
                {
                    b.HasOne("ProductsDishes.DataAccess.Postgres.Models.DailyRationEntity", null)
                        .WithMany()
                        .HasForeignKey("DailyRationsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProductsDishes.DataAccess.Postgres.Models.DishEntity", null)
                        .WithMany()
                        .HasForeignKey("DishesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ProductsDishes.DataAccess.Postgres.Models.DailyRationEntity", b =>
                {
                    b.HasOne("ProductsDishes.DataAccess.Postgres.Models.UserEntity", "User")
                        .WithMany("DailyRations")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ProductsDishes.DataAccess.Postgres.Models.DishIngradientEntity", b =>
                {
                    b.HasOne("ProductsDishes.DataAccess.Postgres.Models.DishEntity", "Dish")
                        .WithMany("Ingredients")
                        .HasForeignKey("DishId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProductsDishes.DataAccess.Postgres.Models.ProductEntity", "Product")
                        .WithMany("DishIngredients")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dish");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("ProductsDishes.DataAccess.Postgres.Models.DishEntity", b =>
                {
                    b.Navigation("Ingredients");
                });

            modelBuilder.Entity("ProductsDishes.DataAccess.Postgres.Models.ProductEntity", b =>
                {
                    b.Navigation("DishIngredients");
                });

            modelBuilder.Entity("ProductsDishes.DataAccess.Postgres.Models.UserEntity", b =>
                {
                    b.Navigation("DailyRations");
                });
#pragma warning restore 612, 618
        }
    }
}
